server:
  port: 9003
spring:
  rabbitmq:
    host: 111.230.226.158
    port: 5672 # 客户界面端：111.230.226.158:15672
    username: songsy
    password: songsy
    virtual-host: /
    publisher-confirms: true #开启 confirm 确认机制
    publisher-returns: true #开启 return 确认机制
    template:
      mandatory: true # 设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
        retry: # 消费端方法如果抛异常了并没有catch之后会每隔6秒重试
          enabled: true
          max-attempts: 3
          initial-interval: 6000
          max-interval: 6000
        prefetch: 20